version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: roudoku-postgres-dev
    environment:
      POSTGRES_DB: roudoku_dev
      POSTGRES_USER: roudoku
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roudoku -d roudoku_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:6-alpine
    container_name: roudoku-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data: