server:
  port: "8080"
  timeout: 30s
  shutdown_timeout: 10s

database:
  host: "localhost"
  port: 5432
  name: "roudoku"
  user: "roudoku"
  password: "roudoku_local_password"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "1h"

logging:
  level: "info"
  format: "json"
  output: "stdout"

external_services:
  google_cloud:
    project_id: "${GOOGLE_CLOUD_PROJECT}"
    credentials_path: "${GOOGLE_APPLICATION_CREDENTIALS}"
  
  tts:
    voice_language: "ja-JP"
    voice_name: "ja-JP-Wavenet-A"
    audio_encoding: "MP3"
    
  storage:
    bucket_name: "${STORAGE_BUCKET_NAME}"