// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUZ3lImAHOHsWjnbKE_VgQFxZI7iujykI',
    appId: '1:439937656316:web:dc0f5ed6a9802e7513fe79',
    messagingSenderId: '439937656316',
    projectId: 'roudoku-mobile-app',
    authDomain: 'roudoku-mobile-app.firebaseapp.com',
    storageBucket: 'roudoku-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAknfiJHj90-iqpqxDO8ams2t-AZHITWGw',
    appId: '1:439937656316:android:671d6ff72cb465ab13fe79',
    messagingSenderId: '439937656316',
    projectId: 'roudoku-mobile-app',
    storageBucket: 'roudoku-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAycQF7FiqoqZlGPgvqXtPoAyxyT9mhfBE',
    appId: '1:439937656316:ios:f5fe0f3d5e074aae13fe79',
    messagingSenderId: '439937656316',
    projectId: 'roudoku-mobile-app',
    storageBucket: 'roudoku-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.roudoku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAycQF7FiqoqZlGPgvqXtPoAyxyT9mhfBE',
    appId: '1:439937656316:ios:f5fe0f3d5e074aae13fe79',
    messagingSenderId: '439937656316',
    projectId: 'roudoku-mobile-app',
    storageBucket: 'roudoku-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.roudoku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUZ3lImAHOHsWjnbKE_VgQFxZI7iujykI',
    appId: '1:439937656316:web:84e8eca72d905bfc13fe79',
    messagingSenderId: '439937656316',
    projectId: 'roudoku-mobile-app',
    authDomain: 'roudoku-mobile-app.firebaseapp.com',
    storageBucket: 'roudoku-mobile-app.firebasestorage.app',
  );
}
